export const projects = [
  {
    id: 1,
    title: "SaaS Landing Page",
    description: "Un landing page usando React y Tailwind",
    image: "/projects/landing-page-saas.png",
    tags: ["React", "TailwindCSS", "TypeScript"],
    demoUrl: "#",
    githubUrl: "https://github.com/LarandaC/landing-page",
  },
  {
    id: 2,
    title: "Bank Landing Page",
    description: "Landing page para un banco usando React y Tailwind",
    image: "/projects/landing-page-banco.png",
    tags: ["React", "TailwindCSS", "TypeScript"],
    demoUrl: "#",
    githubUrl: "https://github.com/LarandaC/landing-page-bank",
  },
  {
    id: 3,
    title: "RESTEplorer",
    description: "Sitio web conectada a la API REST Countries",
    image: "/projects/react-route.png",
    tags: ["React", "React-router", "TailwindCSS", "TypeScript", "RESTful API"],
    demoUrl: "#",
    githubUrl: "https://github.com/LarandaC/paises-react-route",
  },
  {
    id: 4,
    title: "The Simpsons Blog",
    description: "Blog de Los Simpsons usando The Simpsons API",
    image: "/projects/the-simpsons-blog.png",
    tags: ["React", "React-router", "TailwindCSS", "TypeScript", "RESTful API"],
    demoUrl: "https://larandac.github.io/the-simpson-blog/",
    githubUrl: "https://github.com/LarandaC/the-simpson-blog",
  },
];
